name: Build and Push to S3
on: [pull_request]

jobs:
  build:
    name: Build HTML
    runs-on: macos-latest
    steps:
        - uses: actions/checkout@v4
        - uses: swift-actions/setup-swift@v2
          with:
            swift-version: ${{ matrix.swift }}
        - uses: actions/cache@v4
          with:
            path: Build/
            key: build-results
        - name: Build & Run
          run: swift build && swift run

  upload:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/cache@v4
          with:
            path: Build/
            key: build-results
        - uses: shallwefootball/s3-upload-action@master
          with:
            aws_key_id: ${{ secrets.AWS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
            aws_bucket: ${{ secrets.AWS_BUCKET }}
            source_dir: 'Build'