name: Build and Push to S3
on: [pull_request]

jobs:
  build:
    name: Build HTML
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10"
      - uses: actions/cache@v4
        with:
          path: Build/
          key: build-results
      - name: Build & Run
        run: swift build && swift run

  upload:
    name: Upload to S3
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v4
        with:
          path: Build/
          key: build-results
      - uses: dvelasquez/deploy-s3-action@main
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets. AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET }}
          BUCKET_PATH: "./"
          DIST_LOCATION_CODE: ./Build
